### ISSUE TITLE
全商品取得API作成

### ISSUE THREAD

**Issue by posiposi** [posiposi/mikatan-knitting-nextjs#6]
## 対応
- 商品全件取得APIを作成する
  - API仕様はOpenAPIに記載する

### エンドポイント
- 全件取得
  - `/items`

### Open APIファイル
https://github.com/posiposi/mikatan-knitting-php/tree/staging/openapi 参照

**Comment by posiposi** [comment]
`swagger-ui`も同時に導入する
`docker-compose.yaml`については既存プロジェクトから拝借する
```
swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/openapi/openapi.yaml
    volumes:
      - ./openapi:/openapi
    ports:
      - '8010:8080'
```
